### ISSUE TITLE
ERROR in EcosystemBalanceCheckMod.F90 using threads for I20TRGSWCNPECACNTBC, I20TRGSWCNPECACNTBC, IELMFATES, BGCEXP_BCRC_CNPECACNT_1850

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4082]
One of the tests reporting on CDASH failed. Originally found on next on cori-knl. And I just repeated the test with same error message using master (Feb 8th). I repeated without threads and the run completes.  Also verified same error on chrysalis when using threads.

```
 96:  column pbalance error =   4.597668636147019E-008       26106
 96:  Latdeg,Londeg=   57.7894736842104        82.5000000000000     
 96:  begpb       =    65.7470775719049     
 96:  endpb       =    65.7470772193789     
 96:  delta store =  -3.525259586467655E-007
 96:  input mass  =   8.345210933030174E-008
 96:  output mass =   3.900013816155970E-007
 96:  net flux    =  -3.065492722852953E-007
 96:  ptol_pflux: =   1.279770415599154E-005
 96:  sminp_to_plant: =   3.338988757293118E-004
 96:  primp_to_labilep =   8.345210933030174E-008
 96:  supplement_to_sminp =   0.000000000000000E+000
 96:  secondp_to_occlp =   3.024366567225183E-008
 96:  sminp_leached =   3.597577145287063E-007
 96:  ENDRUN:
 96:  ERROR in EcosystemBalanceCheckMod.F90 at line 751                              
 96:                                                                                 
 96:                                                                                 
 96:                                                                                 
 96:                                                                                 
 96:                                                                                 
 96:                                        
 96:  ERROR: Unknown error submitted to shr_abort_abort.
 96: Image              PC                Routine            Line        Source             
 96: e3sm.exe           0000000002BC8DFA  Unknown               Unknown  Unknown
 96: e3sm.exe           00000000010E287E  shr_abort_mod_mp_         114  shr_abort_mod.F90
 96: e3sm.exe           000000000050D9EF  abortutils_mp_end          43  abortutils.F90
 96: e3sm.exe           0000000000B4FBA0  ecosystembalancec         751  EcosystemBalanceCheckMod.F90
 96: e3sm.exe           0000000000520B2E  elm_driver_mp_elm        1311  elm_driver.F90
 96: e3sm.exe           000000000168CDE3  Unknown               Unknown  Unknown
 96: e3sm.exe           000000000163708A  Unknown               Unknown  Unknown
 96: e3sm.exe           00000000016360E1  Unknown               Unknown  Unknown

/global/cscratch1/sd/e3smtest/e3sm_scratch/cori-knl/ERS.f19_g16.I20TRGSWCNPECACNTBC.cori-knl_intel.elm-eca_f19_g16_I20TRGSWCNPECACNTBC.JNextDeveloper20210205_090830

master:
/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/m51-feb8/ERS.f19_g16.I20TRGSWCNPECACNTBC.cori-knl_intel.elm-eca_f19_g16_I20TRGSWCNPECACNTBC.20210208_110604_nf3rd8
```

Testing with 1 thread does NOT exhibit this error.

**Comment by rljacob** [comment]
Not seen on other tests because cori is only one that uses threading.

**Comment by rgknox** [comment]
Since threading issues are so tricky, it might be useful run the simulation for 1 timestep in both threaded and non-threaded mode, and kill it during the balance check and compare the list of flux terms.  Hopefully a short list of terms (or maybe 1) will be different, and can help us narrow it down?

**Comment by ndkeen** [comment]
```
Case with threads:
/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/m51-feb8/ERS.f19_g16.I20TRGSWCNPECACNTBC.cori-knl_intel.elm-eca_f19_g16_I20TRGSWCNPECACNTBC.20210208_110604_nf3rd8

Case without threads:
/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/m51-feb8/ERS_PMx1.f19_g16.I20TRGSWCNPECACNTBC.cori-knl_intel.elm-eca_f19_g16_I20TRGSWCNPECACNTBC.20210209_110330_h29yz6
```

You can find the same 2 cases (ie case with and without threads) in this directory for the other similar error with threads `ERS.f19_g16.I1850GSWCNPECACNTBC.cori-knl_intel.elm-eca_f19_g16_I1850GSWCNPECACNTBC`

**Comment by amametjanov** [comment]
A similar error is reported when running `SMS_Ld2.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.chrysalis_intel.elm-bgcexp` with threads: 256 MPI tasks x 2 OMP threads with 32x2 on-node on 8 Chrysalis nodes
```
 12:  column pbalance error =   1.017969162546643E-008       11445
 12:  Latdeg,Londeg=  -6.62581661374927        144.000000000000
 12:  begpb       =   0.128466330900364
 12:  endpb       =   0.128466320723521
 12:  delta store =  -1.017684320148149E-008
 12:  input mass  =   2.848789018566426E-012
 12:  output mass =   3.650336243212772E-016
 12:  net flux    =   2.848423984942105E-012
 12:  ptol_pflux: =   1.884563365332780E-006
 12:  sminp_to_plant: =   2.430167816423507E-009
 12:  primp_to_labilep =   2.848789018566426E-012
 12:  supplement_to_sminp =   0.000000000000000E+000
 12:  secondp_to_occlp =   2.742425605706252E-020
 12:  sminp_leached =   3.650062000652201E-016
 12:  ENDRUN:
 12:  ERROR in EcosystemBalanceCheckMod.F90 at line 751
 12:
 12:  ERROR: Unknown error submitted to shr_abort_abort.
 12: Image              PC                Routine            Line        Source
 12: libpnetcdf.so.3.0  0000155550C6225A  tracebackqq_          Unknown  Unknown
 12: e3sm.exe           00000000037B87C7  shr_abort_mod_mp_         114  shr_abort_mod.F90
 12: e3sm.exe           00000000021C59E7  abortutils_mp_end          43  abortutils.F90
 12: e3sm.exe           00000000027C7065  ecosystembalancec         751  EcosystemBalanceCheckMod.F90
 12: e3sm.exe           00000000021D6EC8  elm_driver_mp_elm        1311  elm_driver.F90
 12: libiomp5.so        00001555511803F3  __kmp_invoke_micr     Unknown  Unknown
 12: libiomp5.so        0000155551104273  Unknown               Unknown  Unknown
 12: libiomp5.so        0000155551105CB5  __kmp_fork_call       Unknown  Unknown
 12: libiomp5.so        00001555510C8533  __kmpc_fork_call      Unknown  Unknown
 12: e3sm.exe           00000000021CF6C0  elm_driver_mp_elm         617  elm_driver.F90
 12: e3sm.exe           00000000021BBB59  lnd_comp_mct_mp_l         501  lnd_comp_mct.F90
 12: e3sm.exe           000000000043DB54  component_mod_mp_         737  component_mod.F90
 12: e3sm.exe           000000000041FAF0  cime_comp_mod_mp_        2812  cime_comp_mod.F90
 12: e3sm.exe           000000000043D77A  MAIN__                    153  cime_driver.F90
```

**Comment by amametjanov** [comment]
`ERS_Ld20_P128x2.f45_f45.IELMFATES.cori-knl_intel.elm-fates` runs into error in EcosystemBalanceCheckMod.F90 too, but at a different line:
```
125:  column cbalance error =  -3.902266470069055E-008       17850
125:  Latdeg,Londeg         =   -78.0000000000000        185.000000000000
125:  input                 =   0.000000000000000E+000
125:  output                =   1.296461685255442E-007
125:  er                    =   5.118203643668813E-007  5.118203643668813E-007
125:  fire                  =   0.000000000000000E+000
125:  hrv_to_atm            =   0.000000000000000E+000
125:  leach                 =   0.000000000000000E+000
125:  begcb                 =    2.89129495969970
125:  endcb                 =    2.89129444787934
125:  totsomc               =    2.89129444787909
125:  delta store           =  -5.118203647569430E-007
125:  ENDRUN:
125:  ERROR in EcosystemBalanceCheckMod.F90 at line 312
125:
125:  ERROR: Unknown error submitted to shr_abort_abort.
125: GPTLstopf thread 0: timer for l:CNUpdate1 had not been started.
125: GPTLstopf thread 1: timer for l:CNUpdate1 had not been started.
125: Image              PC                Routine            Line        Source
125: e3sm.exe           0000000002BF8DFA  Unknown               Unknown  Unknown
125: e3sm.exe           00000000010E864E  shr_abort_mod_mp_         114  shr_abort_mod.F90
125: e3sm.exe           000000000050E16F  abortutils_mp_end          43  abortutils.F90
125: e3sm.exe           0000000000B510B0  ecosystembalancec         312  EcosystemBalanceCheckMod.F90
125: e3sm.exe           0000000000521166  elm_driver_mp_elm        1303  elm_driver.F90
125: e3sm.exe           00000000016BCDE3  Unknown               Unknown  Unknown
```

**Comment by rljacob** [comment]
Data point: these ECA cases CAN run with threads:
ERS.f19_g16.I1850CNECACNTBC.chrysalis_intel.elm-eca
ERS.f19_g16.I1850CNECACTCBC.chrysalis_intel.elm-eca

Its the "CNPECACNT" cases that are giving runtime errors.

**Comment by rljacob** [comment]
Analysis in #4083 says that PR #3990 caused this.

**Comment by rgknox** [comment]
Testing out a fix now:

I noticed that I accidentally changed how we zero out an array, where previously the zero'ing was constrained to the clump (ie the thread), and in the update I zero'd over the whole allocatable space.  This should indeed over-write sectors outside of its thread (doh!).  Hopefully this fixes it.

https://github.com/E3SM-Project/E3SM/blob/master/components/elm/src/biogeochem/PhosphorusDynamicsMod.F90#L668

**Comment by rgknox** [comment]
See changes in #4194.  I used the following test to reproduce and fix an error:
ERS_P128x2.f19_g16.I1850GSWCNPECACNTBC.machine_intel.elm-eca_f19_g16_I1850GSWCNPECACNTBC

I ran on the following branch-points with the following results:
1) on the commit that was the parent to #3990 d406ae7, result: PASS
2) on current master, result: FAIL
3) with changes in #4194, result PASS

**Comment by rgknox** [comment]
@amametjanov , I suspect that  ERS_Ld20_P128x2.f45_f45.IELMFATES.cori-knl_intel.elm-fates  might start passing with #4194 and #4157

**Comment by rgknox** [comment]
Note, my process also lead me to run this test:

ERS_Ld10.f19_g16.I1850CNPECACNTBC.machine_intel

However, I found this test was failing COMPARE_base_rest even on hash: d406ae7 , and with the fix in #4194

**Comment by amametjanov** [comment]
The two PRs merged locally fix 3 out of 4 fails on Chrysalis. `IELMFATES` in `128x2` mode is still failing at the same location.
```
$ ./cime/scripts/create_test -c -b master
ERS.f19_g16.I1850GSWCNPECACNTBC.chrysalis_intel.elm-eca_f19_g16_I1850GSWCNPECACNTBC
ERS.f19_g16.I20TRGSWCNPECACNTBC.chrysalis_intel.elm-eca_f19_g16_I20TRGSWCNPECACNTBC
ERS_Ld20.f45_f45.IELMFATES.chrysalis_intel.elm-fates
SMS_Ld2.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.chrysalis_intel.elm-bgcexp
...
$ ./cs.status.20210401_194635_0gt0hk | grep "Overall:"
  ERS.f19_g16.I1850GSWCNPECACNTBC.chrysalis_intel.elm-eca_f19_g16_I1850GSWCNPECACNTBC (Overall: PASS) details:
  ERS.f19_g16.I20TRGSWCNPECACNTBC.chrysalis_intel.elm-eca_f19_g16_I20TRGSWCNPECACNTBC (Overall: PASS) details:
  ERS_Ld20.f45_f45.IELMFATES.chrysalis_intel.elm-fates (Overall: FAIL) details:
  SMS_Ld2.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.chrysalis_intel.elm-bgcexp (Overall: DIFF) details:
```

**Comment by rgknox** [comment]
ERS_Ld20_P128x2.f45_f45.IELMED.lawrencium-l6_intel.elm-fates is all PASS on d406ae7
so it looks like that one was a regression with #3990

**Comment by rljacob** [comment]
The IELMFATES test still has a runtime fail with threading.  The rest are fixed.

**Comment by ndkeen** [comment]
I can't test some of these due to https://github.com/E3SM-Project/E3SM/issues/4245, but indeed `ERS_Ld20_P128x2.f45_f45.IELMFATES.cori-knl_intel.elm-fates` is still failing (with Apr22nd master).

`ERS_Ld20.f45_f45.IELMFATES.cori-knl_intel.elm-fates` works, but doesn't use threads.

**Comment by ndkeen** [comment]
Does it make sense to close this issue and open a new one just for `ERS_Ld20_P128x2.f45_f45.IELMFATES.cori-knl_intel.elm-fates` to clean this up?

**Comment by rljacob** [comment]
Yes.  FATES issue is now in #4283
