### ISSUE TITLE
On maint-2.0, need a missing header file in externals/scorpio with Intel compiler

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#5830]
We recently added Intel compiler to the maint-2.0 branch.
To build with intel, it seems to need 
```
#include "spio_io_summary.h"
```
added to `externals/scorpio/src/clib/pio_lists.c`

**Comment by jayeshkrishna** [comment]
This was an issue that was fixed in SCORPIO master (and recent releases), we might need to upgrade the version of SCORPIO in the maint branch.

**Comment by ndkeen** [comment]
Another issue with the scorpio in maint-2.0 on pm-cpu, is that the output netcdf files do not seem to have lustre file stripe settings.

@mahf708 found that updating the scorpio submodule in maint-2.0 can fix both the header and file stripe issue. I'm not sure if it's otherwise ok to update the submodule.

**Comment by ndkeen** [comment]
I am wanting to make intel the default compiler on this branch.

**Comment by dhruvakulkarni** [comment]
Just a note: Users on perlmutter @ NERSC have also observed this issue while installing E3SM.

**Comment by ndkeen** [comment]
This was fixed by https://github.com/E3SM-Project/E3SM/pull/5983

**Comment by jinboxie** [comment]
Hi Noel, was this updated to the maint2.0 branch?
I used the most recent version of maint2.0 on perlmutter, and the problem persists. 
The commit is as follows:
commit 5a3fe8970ac3a3fdf02bc2692cd6e6a1883e5035 (HEAD)
Author: Peter Schwartz <schwartzpd@ornl.gov>
Date:   Tue Feb 6 12:12:06 2024 -0500

    Changed finidat file for wcprodssp tests.

Luckily I saw this page, and added the header as you indicated and it passed.

**Comment by rljacob** [comment]
@jayeshkrishna please verify that the problem is still fixed on latest maint-2.0

**Comment by jayeshkrishna** [comment]
@jinboxie : I just verified that this fix is available on maint-2.0 (https://github.com/E3SM-Project/E3SM/commit/5a3fe8970ac3a3fdf02bc2692cd6e6a1883e5035) . Did you ensure that you updated the submodules in your branch/code (git submodule sync; git submodule update --init --recursive)?

**Comment by jinboxie** [comment]
Hi Jayeshi @jayeshkrishna . The header problem is due to my old E3SM scorpio library. I tried a completely new E3SM maint-2.0 using your command of update gets the latest SCORPIO version and solves the header problem.
There's another problem, though, with the Maint2.0 that does not seems to be solved. As I'm trying to use the maint-2.0 with E3SMv2.0 [amip simulations](https://acme-climate.atlassian.net/wiki/spaces/EWCG/pages/3174924293/v2.LR.amip) here to produce a "branch run", the model is stuck after running for a month and with error mostly from history file output and pio, the issues is posted here (https://github.com/E3SM-Project/E3SM/issues/6255), I wonder if there was reported problem on this issue?
