### ISSUE TITLE
Runtime error on pm-cpu with older branches (like maint-2.1) `open_fabric:No data available`

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#7623]
I'm told this is a known issue where combinations of older versions are no longer working with current libfabric that happend after Aug20 maintenance.  Also note that this is unrelated to another issue after maint: https://github.com/E3SM-Project/E3SM/pull/7622 as the older branches don't even try loading evp-patch module.

The error one see is immediate, at least for 
`SMS.ne30pg2_r05_oECv3.F20TR.pm-cpu_intel.eam-wcprod`
with maint-2.1:

```
 59: MPICH ERROR [Rank 0] [job id 41871182.0] [Thu Aug 21 09:59:36 2025] [nid004919] - Abort(1616271) (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
 59: MPIR_Init_thread(170).......: 
 59: MPID_Init(501)..............: 
 59: MPIDI_OFI_mpi_init_hook(573): 
 59: open_fabric(1521)...........: OFI fi_getinfo() failed (ofi_init.c:1521:open_fabric:No data available)
```

So far I've tried increasing cray-mpich version (8.1.26 and 8.1.27).
As well as trying craype/2.7.32, but both see same error.

**Comment by ndkeen** [comment]
I made a little progress. One change we made (https://github.com/E3SM-Project/E3SM/pull/7144) was a bit of a hack to avoid an issue with nf_open'ing files (error presented as hdf version issue, but it's really a netcdf open issue). We set
```
LD_LIBRARY_PATH=ENV{CRAY_LD_LIBRARY_PATH}:$ENV{LD_LIBRARY_PATH}
```
If I comment this out, the run continues beyond that libfabric issue, but then hits the errors that we had originally resolved with this LD_LIB_PATH work-around.  To find a solution, I found the exact nf_open lines in the fortran, added print statements to see which file it was trying to open, and sure enough the files being read that cause errors are in netcdf4 format.  Changing two of them to cdf5, allowed at least
`SMS.ne30pg2_r05_oECv3.F20TR.pm-cpu_intel.eam-wcprod`
to complete.

That was still with updated cray-mpich/craype modules, so trying without now to find smallest possible change needed.
It may be that we just need to find all netcdf4 files that cases of interest are reading and convert them.
But of course, this brings up issues about consistency between the svn server and NERSC inputdata.
OK I think we still need `cray-mpich/8.1.27`.  But might as well make some other inert changes to keep some
consistency with current master.  I've made a branch and will test with `e3sm_prod` suite.

The two files I needed to change for that test are below.  But there have been others we've applied this fix to as well.

```
(e3sm_unified_1.11.1_login) perlmutter-login21% ll /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP-1-2-0_Annual_Global_0000-2014_c20180105.*
-rw-rw-r--+ 1 ndk ndk 105108 Mar 20 14:05 /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP-1-2-0_Annual_Global_0000-2014_c20180105.cdf5.nc
-rw-rw-r--+ 1 ndk ndk 105108 Aug 21 12:24 /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP-1-2-0_Annual_Global_0000-2014_c20180105.nc
-rw-rw-r--+ 1 ndk ndk 862994 Mar 12 18:47 /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP-1-2-0_Annual_Global_0000-2014_c20180105.netcdf4.nc


(e3sm_unified_1.11.1_login) perlmutter-login21% ll /global/cfs/cdirs/e3sm/inputdata/ocn/docn7/SSTDATA/sst_ice_CMIP6_DECK_E3SM_1x1_c20180213.*
-rw-rw-r--+ 1 ndk   ndk  1848168896 Aug 21 12:50 /global/cfs/cdirs/e3sm/inputdata/ocn/docn7/SSTDATA/sst_ice_CMIP6_DECK_E3SM_1x1_c20180213.cdf5.nc
-rw-rw-r--+ 1 golaz e3sm 1848168896 Aug 21 12:50 /global/cfs/cdirs/e3sm/inputdata/ocn/docn7/SSTDATA/sst_ice_CMIP6_DECK_E3SM_1x1_c20180213.nc
-rw-rw-r--+ 1 ndk   ndk   649534025 Aug 21 12:50 /global/cfs/cdirs/e3sm/inputdata/ocn/docn7/SSTDATA/sst_ice_CMIP6_DECK_E3SM_1x1_c20180213.netcdf4.nc

(e3sm_unified_1.11.1_login) perlmutter-login11% ll /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP6_1pctCO2_c20180216.*
-rw-rw-r--+ 1 ndk ndk   18408 Aug 21 14:49 /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP6_1pctCO2_c20180216.cdf5.nc
-rw-rw-r--+ 1 pjc e3sm  18408 Aug 21 14:50 /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP6_1pctCO2_c20180216.nc
-rw-rw-r--+ 1 ndk ndk  137359 Aug 21 14:50 /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP6_1pctCO2_c20180216.netcdf4.nc

(e3sm_unified_1.11.1_login) perlmutter-login11% ll  /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP_SSP370-1-2-1_Annual_Global_2015-2500_c20210509.*
-rw-rw-r--+ 1 ndk      ndk  43776 Aug 21 14:53 /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP_SSP370-1-2-1_Annual_Global_2015-2500_c20210509.cdf5.nc
-rw-rw-r--+ 1 jjbenedi e3sm 43776 Aug 21 14:53 /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP_SSP370-1-2-1_Annual_Global_2015-2500_c20210509.nc
-rw-rw-r--+ 1 ndk      ndk  89531 Aug 21 14:53 /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP_SSP370-1-2-1_Annual_Global_2015-2500_c20210509.netcdf4.nc

(e3sm_unified_1.11.1_login) perlmutter-login11% ll /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP_SSP585-1-2-1_Annual_Global_2015-2500_c20190310.*
-rw-rw-r--+ 1 ndk ndk  43940 Aug 21 15:00 /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP_SSP585-1-2-1_Annual_Global_2015-2500_c20190310.cdf5.nc
-rw-rw-r--+ 1 pjc pjc  43940 Aug 21 15:00 /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP_SSP585-1-2-1_Annual_Global_2015-2500_c20190310.nc
-rw-rw-r--+ 1 ndk ndk 127572 Aug 21 15:00 /global/cfs/cdirs/e3sm/inputdata/atm/cam/ggas/GHG_CMIP_SSP585-1-2-1_Annual_Global_2015-2500_c20190310.netcdf4.nc

```

**Comment by xylar** [comment]
> It may be that we just need to find all netcdf4 files that cases of interest are reading and convert them.
But of course, this brings up issues about consistency between the svn server and NERSC inputdata.

@ndkeen, we've dealt with NetCDF4 files slipping through the cracks many times.  The correct solution has typically been to convert them to CDF5 on the LCRC inputdata server and give them a new datestamp (both the file itself and the reference to it in E3SM).  Then, the new file will be downloaded to NERSC (and elsewhere automatically).

cc @rljacob

**Comment by ndkeen** [comment]
Note that each case might need to read different files than those I'm testing in e3sm_prod suite.
If you get hdf5 version error, you will need to find the offending file.
https://github.com/E3SM-Project/E3SM/issues/7625

**Comment by ndkeen** [comment]
I've dealt with them long before. The claim was it was fixed. 

It seems to me there is a huge issue with whatever tool is *creating* the netcdf files in netcdf4 to begin with.
As those are then added to inputdata.

**Comment by xylar** [comment]
> It seems to me there is a huge issue with whatever tool is creating the netcdf files in netcdf4 to begin with.
As those are then added to inputdata.

Unfortunately, NetCDF4 is the default format for a lot of tools.  (It's a much better and more flexible format outside of E3SM.) So it takes real dedication to make sure that every file gets written out in NetCDF3 formats (e.g. CDF5 instead).  We do try, but files sometimes slip through the cracks.

**Comment by rljacob** [comment]
I think you also have to delete the file locally to force a download from the server.  Not sure it checks the datestamp.

**Comment by xylar** [comment]
@rljacob, I was meaning the datestamp in the filename.  That it would presumably have to check, no?

**Comment by rljacob** [comment]
Yes but then you also need a code change for the namelists to point to that new filename.   For changing from NetCDF4 to NetCDF3, its fine to keep the filename identical.

**Comment by xylar** [comment]
> Yes but then you also need a code change for the namelists to point to that new filename. For changing from NetCDF4 to NetCDF3, its fine to keep the filename identical.

That seems troubling to me because then it's hard to keep track of which machines have a correct NetCDF3 files and which have a bad NetCDF4 file.  It seems better to make the code change and download a new filename.

But I will defer to you.  You have a lot more expertise in this stuff than I do.

**Comment by ndkeen** [comment]
Note I merged the PR to maint-2.1 (https://github.com/E3SM-Project/E3SM/pull/7627), but I am now seeing I get the original error with gnu compiler.
I wanted to get this change in asap, and may also need to correct other maint branches.
Can make another issue for gnu.

I'm sure we can improve the current situation regarding file formats.
Note that I get we don't want netcdf4 formats, but the code was working fine reading these in the past (and still does with master), so I think it's also worth pursuing both:
a) improve netcdf4 situation (correcting at source, on local machines, protocols for adding files, etc)
b) still allow machines to read them

**Comment by jennykowalcz** [comment]
Hi @ndkeen! Thanks for your work on this issue. I'm coming back to this after being away last week.  (By "this" I mean trying to figure out why a case that was running pre-Aug20 maintenance won't run now.) I cherry-picked your commits https://github.com/E3SM-Project/E3SM/pull/7618/commits and https://github.com/E3SM-Project/E3SM/pull/7627/commits to my old E3SM branch and remade the case, but it still fails with errors that appear to be related to the netcdf4 / 5 issue. 

Would you recommend a) recreating the case with a newer branch of E3SM, or b) figuring out which files in the netcdf4 format it is trying to read in and converting these to cdf5?  If a), can you recommend which newer branch to use? I'm sorry for my ignorance here -- thanks for your help!

**Comment by BunnyVon** [comment]
@ndkeen , I still have the ` 6810: open_fabric(1521)...........: OFI fi_getinfo() failed (ofi_init.c:1521:open_fabric:No data available)` issue after I applied the same strategy @jennykowalcz mentioned above.

**Comment by ndkeen** [comment]
Note that I also see this error with gnu compiler on maint-2.1 and I'm working on a branch to correct that.
But it should be working with intel compiler. To determine between:
a) it's still broken, need more work on maint-2.1
b) the method used to apply change and resubmit is somehow not accepting the change
we could try to do a stand-alone test with the checkout.
In the checkout where these changes are applied
(or better, do fresh checkout of maint-2.1 branch separately to test this), try:

```
cd cime/scripts
create_test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod
```

**Comment by jennykowalcz** [comment]
> Note that I also see this error with gnu compiler on maint-2.1 and I'm working on a branch to correct that. But it should be working with intel compiler. To determine between: a) it's still broken, need more work on maint-2.1 b) the method used to apply change and resubmit is somehow not accepting the change we could try to do a stand-alone test with the checkout. In the checkout where these changes are applied (or better, do fresh checkout of maint-2.1 branch separately to test this), try:
> 
> ```
> cd cime/scripts
> create_test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod
> ```


This gives
```
`jkowalcz@login31:/global/u2/j/jkowalcz/E3SM-hydro-test/E3SM/cime/scripts> ./create_test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod
Using project from config_machines.xml: e3sm
create_test will do up to 1 tasks simultaneously
create_test will use up to 320 cores simultaneously
Creating test directory /pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2
RUNNING TESTS:
  SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod
Starting CREATE_NEWCASE for test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod with 1 procs
Finished CREATE_NEWCASE for test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod in 6.730145 seconds (PASS)
Starting XML for test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod with 1 procs
Finished XML for test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod in 0.431622 seconds (PASS)
Starting SETUP for test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod with 1 procs
Finished SETUP for test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod in 6.267179 seconds (PASS)
Starting SHAREDLIB_BUILD for test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod with 1 procs
Finished SHAREDLIB_BUILD for test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod in 109.372604 seconds (PASS)
Starting MODEL_BUILD for test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod with 7 procs
Finished MODEL_BUILD for test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod in 406.515498 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2
    Errors were:
        Building test for SMS in directory /pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2
        ERROR: BUILD FAIL: build e3sm failed, cat /pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2/bld/e3sm.bldlog.250905-070221

Waiting for tests to finish
FAIL SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod (phase MODEL_BUILD)
    Case dir: /pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2
Due to presence of batch system, create_test will exit before tests are complete.
To force create_test to wait for full completion, use --wait
test-scheduler took 531.0343825817108 seconds`
```

The end of the build log has:
```
`ld: /pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2/bld/intel/mpich/nodebug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/csm_share/libcsm_share.a(shr_vmath_mod.F90.o): in function `shr_vmath_mod_mp_shr_vmath_sqrt_':
/global/u2/j/jkowalcz/E3SM-hydro-test/E3SM/share/util/shr_vmath_mod.F90:44:(.text+0x27): undefined reference to `vdsqrt_'
ld: /pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2/bld/intel/mpich/nodebug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/csm_share/libcsm_share.a(shr_vmath_mod.F90.o): in function `shr_vmath_mod_mp_shr_vmath_exp_':
/global/u2/j/jkowalcz/E3SM-hydro-test/E3SM/share/util/shr_vmath_mod.F90:105:(.text+0x1b7): undefined reference to `vdexp_'
ld: /pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2/bld/intel/mpich/nodebug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/csm_share/libcsm_share.a(shr_vmath_mod.F90.o): in function `shr_vmath_mod_mp_shr_vmath_div_':
/global/u2/j/jkowalcz/E3SM-hydro-test/E3SM/share/util/shr_vmath_mod.F90:130:(.text+0x1da): undefined reference to `vddiv_'
ld: /pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2/bld/intel/mpich/nodebug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/csm_share/libcsm_share.a(shr_vmath_mod.F90.o): in function `shr_vmath_mod_mp_shr_vmath_log_':
/global/u2/j/jkowalcz/E3SM-hydro-test/E3SM/share/util/shr_vmath_mod.F90:164:(.text+0x1f7): undefined reference to `vdln_'
ld: /pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2/bld/intel/mpich/nodebug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/csm_share/libcsm_share.a(shr_vmath_mod.F90.o): in function `shr_vmath_mod_mp_shr_vmath_sin_':
/global/u2/j/jkowalcz/E3SM-hydro-test/E3SM/share/util/shr_vmath_mod.F90:194:(.text+0x217): undefined reference to `vdsin_'
ld: /pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2/bld/intel/mpich/nodebug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/csm_share/libcsm_share.a(shr_vmath_mod.F90.o): in function `shr_vmath_mod_mp_shr_vmath_cos_':
/global/u2/j/jkowalcz/E3SM-hydro-test/E3SM/share/util/shr_vmath_mod.F90:222:(.text+0x237): undefined reference to `vdcos_'
Target /pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2/bld/e3sm.exe built in 4.393696 seconds
gmake[2]: *** [cmake/cpl/CMakeFiles/e3sm.exe.dir/build.make:555: /pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2/bld/e3sm.exe] Error 1
gmake[2]: Leaving directory '/pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2/bld/cmake-bld'
gmake[1]: *** [CMakeFiles/Makefile2:662: cmake/cpl/CMakeFiles/e3sm.exe.dir/all] Error 2
gmake[1]: Leaving directory '/pscratch/sd/j/jkowalcz/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_070016_sl92x2/bld/cmake-bld'
gmake: *** [Makefile:94: all] Error 2`

```

This is in my E3SM branch with your two commits cherry-picked. I'll repeat this in a fresh checkout of maint-2.1 now.

**Comment by jennykowalcz** [comment]
The model build passed in a fresh checkout of maint-2.1.

I think the cleanest way forward for me is to recreate my case on a newer E3SM branch!

**Comment by BunnyVon** [comment]
@ndkeen , my errors are different 

```
/global/cfs/cdirs/e3sm/feng809/code/scream_tritium_dev/components/eam/src/physics/p3/eam/micro_p3.F90(71): error #6580: Name in only-list does not exist or is not accessible.   [QV_SAT]
   use wv_sat_scream, only:qv_sat
---------------------------^
/global/cfs/cdirs/e3sm/feng809/code/scream_tritium_dev/components/eam/src/physics/p3/eam/micro_p3.F90(480): error #6404: This name does not have a type, and must have an explicit type.   [QV_SAT]
       qv_sat_l(k)     = qv_sat(t_atm(k),pres(k),0)
-------------------------^
/global/cfs/cdirs/e3sm/feng809/code/scream_tritium_dev/components/eam/src/physics/p3/eam/micro_p3.F90(2428): error #6404: This name does not have a type, and must have an explicit type.   [QV_SAT]
      qsat0 = qv_sat( T_zerodegc,pres,0 )
--------------^
/global/cfs/cdirs/e3sm/feng809/code/scream_tritium_dev/components/eam/src/physics/p3/eam/micro_p3.F90(2478): error #6404: This name does not have a type, and must have an explicit type.   [QV_SAT]
      qsat0=qv_sat( T_zerodegc,pres,0 )
------------^
/global/cfs/cdirs/e3sm/feng809/code/scream_tritium_dev/components/eam/src/physics/p3/eam/micro_p3.F90(3098): error #6404: This name does not have a type, and must have an explicit type.   [QV_SAT]
   qv_sat_l = qv_sat(ttmp_all,pres,0)
--------------^
compilation aborted for /global/cfs/cdirs/e3sm/feng809/code/scream_tritium_dev/components/eam/src/physics/p3/eam/micro_p3.F90 (code 1)
Target CMakeFiles/atm.dir/__/__/eam/src/physics/p3/eam/micro_p3.F90.o built in 0.115878 seconds
gmake[2]: *** [cmake/atm/CMakeFiles/atm.dir/build.make:5823: cmake/atm/CMakeFiles/atm.dir/__/__/eam/src/physics/p3/eam/micro_p3.F90.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
/pscratch/sd/f/feng809/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_095310_pjhg8e/bld/cmake-bld/core_seaice/model_forward/mpas_seaice_core_interface.f90(163): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [IERR]
   subroutine setup_packages_dynamics(configPool, packagePool, ierr)!{{{
---------------------------------------------------------------^
Target CMakeFiles/atm.dir/__/__/eam/src/chemistry/mozart/mo_fstrat.F90.o built in 0.834836 seconds
Target CMakeFiles/atm.dir/__/__/eam/src/physics/cam/physics_types.F90.o built in 2.868887 seconds
Target CMakeFiles/atm.dir/__/__/eam/src/physics/cam/pkg_cld_sediment.F90.o built in 0.917540 seconds
Target CMakeFiles/atm.dir/__/__/eam/src/physics/cam/shoc.F90.o built in 3.066722 seconds
/pscratch/sd/f/feng809/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_095310_pjhg8e/bld/cmake-bld/core_seaice/model_forward/mpas_seaice_core_interface.f90(1): warning #5462: Global name too long, shortened from: seaice_core_interface_mp_seaice_setup_decomposed_dimensions_$blk.mpi_constants_mp_mpi_unweighted_ to: eaice_core_interface_mp_seaice_setup_decomposed_dimensions_$blk.mpi_constants_mp_mpi_unweighted_

^
/pscratch/sd/f/feng809/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_095310_pjhg8e/bld/cmake-bld/core_seaice/model_forward/mpas_seaice_core_interface.f90(1): warning #5462: Global name too long, shortened from: seaice_core_interface_mp_seaice_setup_decomposed_dimensions_$blk.mpi_constants_mp_mpi_weights_empty_ to: ce_core_interface_mp_seaice_setup_decomposed_dimensions_$blk.mpi_constants_mp_mpi_weights_empty_

^
/pscratch/sd/f/feng809/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_095310_pjhg8e/bld/cmake-bld/core_seaice/model_forward/mpas_seaice_core_interface.f90(1): warning #5462: Global name too long, shortened from: seaice_core_interface_mp_seaice_setup_decomposed_dimensions_$blk.mpi_constants_mp_mpi_status_ignore_ to: ce_core_interface_mp_seaice_setup_decomposed_dimensions_$blk.mpi_constants_mp_mpi_status_ignore_

^
/pscratch/sd/f/feng809/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_095310_pjhg8e/bld/cmake-bld/core_seaice/model_forward/mpas_seaice_core_interface.f90(1): warning #5462: Global name too long, shortened from: seaice_core_interface_mp_seaice_setup_decomposed_dimensions_$blk.mpi_constants_mp_mpi_statuses_ignore_ to: _core_interface_mp_seaice_setup_decomposed_dimensions_$blk.mpi_constants_mp_mpi_statuses_ignore_

^
/pscratch/sd/f/feng809/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_095310_pjhg8e/bld/cmake-bld/core_seaice/model_forward/mpas_seaice_core_interface.f90(1): warning #5462: Global name too long, shortened from: seaice_core_interface_mp_seaice_setup_decomposed_dimensions_$blk.mpi_constants_mp_mpi_errcodes_ignore_ to: _core_interface_mp_seaice_setup_decomposed_dimensions_$blk.mpi_constants_mp_mpi_errcodes_ignore_

^
/pscratch/sd/f/feng809/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_095310_pjhg8e/bld/cmake-bld/core_seaice/model_forward/mpas_seaice_core_interface.f90(1): warning #5462: Global name too long, shortened from: seaice_core_interface_mp_seaice_setup_decomposed_dimensions_$blk.mpi_constants_mp_mpi_argvs_null_ to: eaice_core_interface_mp_seaice_setup_decomposed_dimensions_$blk.mpi_constants_mp_mpi_argvs_null_

^
Target CMakeFiles/atm.dir/__/__/eam/src/physics/cosp2/local/cosp.F90.o built in 52.270917 seconds
gmake[2]: Leaving directory '/pscratch/sd/f/feng809/e3sm_scratch/pm-cpu/SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod.20250905_095310_pjhg8e/bld/cmake-bld'
gmake[1]: *** [CMakeFiles/Makefile2:444: cmake/atm/CMakeFiles/atm.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```

**Comment by ndkeen** [comment]
Can you try: 
```
git clone -b maint-2.1 git@github.com:E3SM-Project/E3SM m21
cd m21
git submodule update --recursive --init
cd cime/scripts
create_test SMS_Ln5.ne30pg2_r05_oECv3.F2010.pm-cpu_intel.eam-wcprod
```

I just did this and the test passes.

(Note, I just merged a PR to maint-2.1, but it will only affect GNU builds)

**Comment by BunnyVon** [comment]
@ndkeen , my old simulation was able to run without any errors after I applied the changes in your commits to my code. Thank you so much Noel!

**Comment by ndkeen** [comment]
Closing as these 2 PR's allowed tests to run on maint-2.1

https://github.com/E3SM-Project/E3SM/pull/7627
https://github.com/E3SM-Project/E3SM/pull/7671
